# Generated by Django 6.0.2 on 2026-03-02 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_sessions',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat_session',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('ia', 'asistente')], default='user', max_length=10)),
                ('contenido', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_talk.chat_sessions')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
